bezier = linear, 1, 1, 0, 0
animation = fade, 1, 1.8, linear
hide_cursor = true
general {
    hide_cursor = true
}

input {
    kb_layout = us
    numlock_by_default = true
}

background {
    monitor =
    path = screenshot
    # color = rgba(25, 20, 20, 1.0)
     color = rgba(ff0000ee)
    blur_passes = 5
    noise = 0.1
    brightness = 0.5
    # vibrancy = 0
    # vibrancy_darkness = 0
    # contrast = 0
}


image {
    monitor =
    # path = /home/me/cutie.png
    path = $MAIN_CONFIG_FOLDER/hyprland/wallper.png
    size = 150
    rounding = 0 # no rounding
    border_color = rgba(ff0000ee)

    position = 0, 200
    halign = center
    valign = center
}

shape {
    monitor =
    size = 30%, 60
    color = rgba(A90000ee) # no fill
    rounding = 0 #-1 # circle
    border_size = 4
    border_color = rgba(ff0000ee)

    position = 0, 80
    halign = center
    valign = center
}

input-field {
    font_family = VHS + icons

    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(A90000ee) # no fill

    outer_color = rgba(ff0000ee)# rgba(00ff99ee) 45deg
    check_color=rgba(ff0000ee)# rgba(ff6633ee) 120deg
    fail_color=rgba(ff0000ee)# rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 0 # 15

    position = 0, -20
    halign = center
    valign = center
}

label {
    font_family = VHS + icons


    monitor =
    text = Плотную, $DESC!
    # color = rgba(200, 200, 200, 1.0)
    color = rgba(ffffff)
    font_size = 26
    # font_family = Noto Sans

    position = 0, 80
    halign = center
    valign = center
}
