wallpaper {
    #monitor = HDMI-A-1
    monitor =
    #preload =  ~/Настройки/hyprland/wallper.png
    #wallpaper = ,contain:~/Настройки/hyprland/wallper.png
    path = $MAIN_CONFIG_FOLDER/hyprland/wallper.png
    fit_mode = contain
}
    splash = false
