exec-once = hyprlock
exec-once = hyprpolkitagent & pipewire & dunst
# exec-once = hyprpolkitagent & xdg-desktop-portal-hyprland & pipewire & dunst
exec-once = hyprpaper & quickshell
exec-once = sleep 3 && sunshine & AyuGram -startintray & mpd & sleep 4 && mpdris2-rs -n
