windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}
windowrule = no_initial_focus on, match:class Ardour-9.2.274
windowrule = no_initial_focus on, match:class lmms
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
windowrule {
    name = zenity
    match:class = zenity
    float = yes
}

windowrule = match:class explorer.exe, fullscreen on



windowrule = match:class org.kde.dolphin, float on
windowrule = match:class org.rncbc.qpwgraph, float on
windowrule = match:class org.pulseaudio.pavucontrol, float on
windowrule = match:class org.strawberrymusicplayer.strawberry, float on
windowrule = match:class org-tlauncher-tlauncher-rmo-TLauncher, float on, size 1060 685
windowrule = match:class com.ayugram.desktop, match:title Просмотр медиа.*, float on
windowrule = match:class xdg-desktop-portal-gtk, match:title Сохранить видео*, float on
windowrule = match:class zen, match:title Библиотека|Картинка в картинке, float on
